use_frameworks!

platform :ios, '13.0'

source 'https://github.com/morapelker/tedooo-pod-repo.git'
#source 'https://github.com/CocoaPods/Specs.git'
source 'https://cdn.cocoapods.org/'

target 'SettingsScreenImpl_Example' do
  pod 'SettingsScreenImpl', :path => '../'

  target 'SettingsScreenImpl_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 10.0.0'
  end
end
